// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhl1bDAxcrLJ1KR95NrbBx9sB7XfKQlZQ',
    appId: '1:617739066616:web:98830dc31d8e8c64d62f0d',
    messagingSenderId: '617739066616',
    projectId: 'salla-app-users',
    authDomain: 'salla-app-users.firebaseapp.com',
    storageBucket: 'salla-app-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_QxWCYiov1AcRHUGV2q5mU0InHo5gg8',
    appId: '1:617739066616:android:cc3a6eba8d7bec22d62f0d',
    messagingSenderId: '617739066616',
    projectId: 'salla-app-users',
    storageBucket: 'salla-app-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAC8xmqnacLoR-XfSwY34QzlyfoCoGhE',
    appId: '1:617739066616:ios:0c0cfd972701df16d62f0d',
    messagingSenderId: '617739066616',
    projectId: 'salla-app-users',
    storageBucket: 'salla-app-users.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAC8xmqnacLoR-XfSwY34QzlyfoCoGhE',
    appId: '1:617739066616:ios:020a1536ad1d47e6d62f0d',
    messagingSenderId: '617739066616',
    projectId: 'salla-app-users',
    storageBucket: 'salla-app-users.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
